local lstage=require'lstage'
local s1=lstage.stage()
local s2=lstage.stage()
s1:wrap(function()
   print('calling',s2) 
   s2:call(42)
   print('called',s2)   
end)
s2:wrap(function(i)
   print('s2',i) 
end)

s1:instantiate(1)
s2:instantiate(1)
s1:push()
lstage.event.sleep(1)
